# Generated by Django 4.1.7 on 2023-03-14 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_comment_part_alter_comment_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderscar',
            name='email',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='orderscar',
            name='phoneNumber',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='orderspart',
            name='email',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='orderspart',
            name='phoneNumber',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='orderscar',
            name='car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.car'),
        ),
    ]
